<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="managetree.aspx.cs" Inherits="CmlTechniques.managetree" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>CML Interactive</title>
    <script type="text/javascript">
    
      function pageLoad() {
      }
    
    </script>
     
   <script language="javascript" type="text/javascript">
       function openFrame(_id) {
           myframe.location = "managetreeSub.aspx?id=" + _id ;
       }
                
    </script>
    
</head>
<body bgcolor="#414141" style="padding:0px;margin:0px">
    <form id="form1" runat="server">
    <div >
        <%--<asp:ScriptManager ID="ScriptManager1" runat="server" />--%>
        <asp:ToolkitScriptManager ID="ToolkitScriptManager1" runat="server">
        </asp:ToolkitScriptManager>
        <div style="top:0px;bottom:0px;left:0px;width:300px;position:absolute;overflow:auto;">
        <div>
        <asp:UpdatePanel ID="UpdatePanel1" runat="server">
                    <ContentTemplate>
                     <asp:Button ID="btnrefresh" runat="server" Text="" 
                          style="background-image:url('images/refresh.png');background-repeat:no-repeat;background-color:Transparent; " 
                          BorderStyle="None" Height="20px" Width="20px" 
                          ToolTip="Refresh Folder Tree" onclick="btnrefresh_Click" /> 
                       </ContentTemplate>
                    </asp:UpdatePanel> 
        </div>
        <div>
        <asp:UpdatePanel ID="UpdatePanel3" runat="server">
                        <ContentTemplate>                       
                    <asp:TreeView ID="mytree" runat="server" Width="300px" 
                            onselectednodechanged="mytree_SelectedNodeChanged" Font-Names="Verdana" 
                            Font-Size="Small"                        ShowLines="True" NodeWrap="True" 
                            AutoGenerateDataBindings="False" EnableClientScript="true" ForeColor="White">
                        <SelectedNodeStyle BackColor="#FF9900" />
                    </asp:TreeView>
                        
                    </ContentTemplate>
                        </asp:UpdatePanel>
        </div>
        </div>
        <div style="top:0px;bottom:0px;left:300px;right:0px;position:absolute;overflow:hidden;" >
        <iframe id="myframe" runat="server" name="myframe" frameborder="0" height="100%" width="100%" scrolling="yes"></iframe>
        </div>                 
           
    </div>
    </form>
</body>
</html>
